"""Pre-open refresh and open-gate checks for manual execution plans."""

from __future__ import annotations

import csv
import json
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any
from uuid import UUID, uuid4

from quant_system.decision.reports import DailyReportArtifacts, write_decision_table_report


def load_json_report(path: Path) -> dict[str, Any]:
    """Load a JSON report generated by the daily workbench."""
    with path.open(encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"report must be a JSON object: {path}")
    return payload


def latest_report_path(root: Path, *, stem: str) -> Path | None:
    """Return the latest report path with a given file stem under a report root."""
    paths = sorted(root.glob(f"*/*/{stem}.json"), key=lambda path: path.stat().st_mtime)
    return paths[-1] if paths else None


def load_snapshot(path: Path | None) -> dict[str, dict[str, Any]]:
    """Load optional broker snapshot rows keyed by symbol.

    Supported columns: symbol, last_price, news_risk, liquidity_status, note.
    JSON may be either a list of rows or an object containing a "rows" list.
    """
    if path is None:
        return {}
    if path.suffix.lower() == ".json":
        payload = json.loads(path.read_text(encoding="utf-8"))
        rows = payload.get("rows", payload) if isinstance(payload, dict) else payload
    else:
        with path.open(encoding="utf-8", newline="") as handle:
            rows = list(csv.DictReader(handle))
    if not isinstance(rows, list):
        raise ValueError("snapshot must contain rows")
    snapshot: dict[str, dict[str, Any]] = {}
    for row in rows:
        if not isinstance(row, dict) or not row.get("symbol"):
            continue
        normalized = dict(row)
        normalized["symbol"] = str(row["symbol"]).upper()
        if normalized.get("last_price") not in (None, ""):
            normalized["last_price"] = float(normalized["last_price"])
        snapshot[normalized["symbol"]] = normalized
    return snapshot


def run_preopen_refresh_workflow(
    *,
    premarket_report_path: Path,
    report_root: Path,
    snapshot_path: Path | None = None,
    run_id: UUID | None = None,
    generated_at_utc: datetime | None = None,
) -> tuple[dict[str, Any], DailyReportArtifacts]:
    """Refresh a premarket plan shortly before the order session."""
    run_id = run_id or uuid4()
    generated_at_utc = _ensure_utc(generated_at_utc or datetime.now(UTC))
    premarket = load_json_report(premarket_report_path)
    snapshot = load_snapshot(snapshot_path)
    rows = [
        evaluate_gate_row(
            candidate,
            snapshot=snapshot.get(candidate["symbol"]),
            minutes_before_or_after_open=-10,
        )
        for candidate in premarket.get("candidates", [])
    ]
    signal_session = date.fromisoformat(premarket["metadata"]["signal_session"])
    report = _decision_report(
        run_id=run_id,
        generated_at_utc=generated_at_utc,
        source_report_path=premarket_report_path,
        signal_session=signal_session,
        gate_name="preopen_refresh",
        minutes_before_or_after_open=-10,
        rows=rows,
        snapshot_path=snapshot_path,
    )
    artifacts = _write_with_artifacts(
        report=report,
        rows=rows,
        report_root=report_root,
        signal_session=signal_session,
        run_id=run_id,
        stem="preopen_refresh",
        title="Pre-open Refresh",
    )
    return report, artifacts


def run_open_gate_workflow(
    *,
    premarket_report_path: Path,
    report_root: Path,
    minutes: int,
    snapshot_path: Path | None = None,
    run_id: UUID | None = None,
    generated_at_utc: datetime | None = None,
) -> tuple[dict[str, Any], DailyReportArtifacts]:
    """Evaluate T+30/T+60 execution gates from a premarket report."""
    if minutes not in {30, 60}:
        raise ValueError("open gate minutes must be 30 or 60")
    run_id = run_id or uuid4()
    generated_at_utc = _ensure_utc(generated_at_utc or datetime.now(UTC))
    premarket = load_json_report(premarket_report_path)
    snapshot = load_snapshot(snapshot_path)
    rows = [
        evaluate_gate_row(
            candidate,
            snapshot=snapshot.get(candidate["symbol"]),
            minutes_before_or_after_open=minutes,
        )
        for candidate in premarket.get("candidates", [])
    ]
    signal_session = date.fromisoformat(premarket["metadata"]["signal_session"])
    report = _decision_report(
        run_id=run_id,
        generated_at_utc=generated_at_utc,
        source_report_path=premarket_report_path,
        signal_session=signal_session,
        gate_name=f"open_{minutes}",
        minutes_before_or_after_open=minutes,
        rows=rows,
        snapshot_path=snapshot_path,
    )
    artifacts = _write_with_artifacts(
        report=report,
        rows=rows,
        report_root=report_root,
        signal_session=signal_session,
        run_id=run_id,
        stem=f"open_gate_{minutes}",
        title=f"Open Gate T+{minutes}",
    )
    return report, artifacts


def evaluate_gate_row(
    candidate: dict[str, Any],
    *,
    snapshot: dict[str, Any] | None,
    minutes_before_or_after_open: int,
) -> dict[str, Any]:
    """Return KEEP/REDUCE/DEFER/CANCEL for one candidate."""
    symbol = str(candidate["symbol"]).upper()
    base = {
        "symbol": symbol,
        "signal_id": candidate.get("signal_id"),
        "gate_minute": minutes_before_or_after_open,
        "universe_role": candidate.get("universe_role", "unclassified"),
        "planned_action": candidate.get("recommended_action"),
        "limit_price": candidate.get("limit_price"),
        "max_gap_up_price": candidate.get("max_gap_up_price"),
        "gap_down_cancel_below": candidate.get("gap_down_cancel_below"),
        "last_price": None,
        "decision": "DEFER",
        "reason": "no_intraday_snapshot_available",
        "note": "",
    }
    if candidate.get("recommended_action") == "REVIEW_AS_DEFENSIVE_OVERLAY":
        base["decision"] = "DEFER"
        base["reason"] = "hedge_overlay_requires_manual_context"
    if snapshot is None:
        return base

    base["last_price"] = snapshot.get("last_price")
    base["note"] = snapshot.get("note", "")
    snapshot_news = str(snapshot.get("news_risk", candidate.get("news_risk", "LOW"))).upper()
    liquidity = str(snapshot.get("liquidity_status", "OK")).upper()
    if snapshot_news == "HIGH":
        base["decision"] = "CANCEL"
        base["reason"] = "high_news_risk_snapshot"
        return base
    if snapshot_news == "MEDIUM":
        base["decision"] = "DEFER"
        base["reason"] = "medium_news_risk_snapshot"
        return base
    if liquidity not in {"OK", "NORMAL", ""}:
        base["decision"] = "DEFER"
        base["reason"] = "abnormal_liquidity_snapshot"
        return base
    last_price = snapshot.get("last_price")
    if last_price is None:
        base["decision"] = "DEFER"
        base["reason"] = "missing_last_price_snapshot"
        return base
    if float(last_price) > float(candidate["max_gap_up_price"]):
        base["decision"] = "CANCEL"
        base["reason"] = "gap_up_above_plan"
        return base
    if float(last_price) < float(candidate["gap_down_cancel_below"]):
        base["decision"] = "CANCEL"
        base["reason"] = "gap_down_below_plan"
        return base
    if candidate.get("recommended_action") == "REVIEW_AS_DEFENSIVE_OVERLAY":
        return base
    base["decision"] = "KEEP"
    base["reason"] = "within_price_and_risk_bounds"
    return base


def _decision_report(
    *,
    run_id: UUID,
    generated_at_utc: datetime,
    source_report_path: Path,
    signal_session: date,
    gate_name: str,
    minutes_before_or_after_open: int,
    rows: list[dict[str, Any]],
    snapshot_path: Path | None,
) -> dict[str, Any]:
    counts = {
        "row_count": len(rows),
        "keep_count": sum(row["decision"] == "KEEP" for row in rows),
        "defer_count": sum(row["decision"] == "DEFER" for row in rows),
        "cancel_count": sum(row["decision"] == "CANCEL" for row in rows),
        "reduce_count": sum(row["decision"] == "REDUCE" for row in rows),
    }
    return {
        "metadata": {
            "run_id": str(run_id),
            "generated_at_utc": generated_at_utc.isoformat(),
            "signal_session": signal_session.isoformat(),
            "gate_name": gate_name,
            "minutes_before_or_after_open": minutes_before_or_after_open,
            "source_report_path": str(source_report_path),
            "snapshot_path": str(snapshot_path) if snapshot_path else None,
            "execution_scope": "manual_decision_support_only",
        },
        "counts": counts,
        "rows": rows,
    }


def _write_with_artifacts(
    *,
    report: dict[str, Any],
    rows: list[dict[str, Any]],
    report_root: Path,
    signal_session: date,
    run_id: UUID,
    stem: str,
    title: str,
) -> DailyReportArtifacts:
    artifacts = write_decision_table_report(
        report=report,
        rows=rows,
        report_root=report_root,
        as_of=signal_session,
        run_id=run_id,
        stem=stem,
        title=title,
    )
    report["artifacts"] = {
        "directory": str(artifacts.directory),
        "json": str(artifacts.json_path),
        "csv": str(artifacts.csv_path),
        "markdown": str(artifacts.markdown_path),
        "html": str(artifacts.html_path),
    }
    return write_decision_table_report(
        report=report,
        rows=rows,
        report_root=report_root,
        as_of=signal_session,
        run_id=run_id,
        stem=stem,
        title=title,
    )


def _ensure_utc(value: datetime) -> datetime:
    if value.utcoffset() is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)

